#!/bin/bash
# Environment Export Script
# Generated by Ansible aws-setup role

# Set AWS profile
export AWS_PROFILE="svktek"
export AWS_DEFAULT_REGION="us-east-1"
export AWS_REGION="us-east-1"

# Set environment variables
export ENVIRONMENT="dev"
export TERRAFORM_WORKSPACE="dev"

# Set project variables
export PROJECT_NAME="ROSA-Infrastructure"
export PROJECT_VERSION="1.0.0"

# Set Terraform variables
export TF_VAR_environment="dev"
export TF_VAR_region="us-east-1"

echo "Environment variables set for dev environment"
echo "AWS Region: us-east-1"
echo "Terraform workspace: dev"
