# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: "2025-07-18T08:59:14Z"
  labels:
    app: grafana
    environment: dev
  name: grafana-new
  namespace: monitoring
  resourceVersion: "4189769"
  uid: a98ab944-9a06-4c25-b91b-103e9d8d8927
spec:
  host: grafana.probuddy.us
  port:
    targetPort: 3000
  tls:
    termination: edge
  to:
    kind: Service
    name: grafana
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2025-07-18T10:16:03Z"
      status: "True"
      type: Admitted
    host: grafana.probuddy.us
    routerCanonicalHostname: router-default.apps.o0r9m0f2v7l3b1c.55n4.p1.openshiftapps.com
    routerName: default
    wildcardPolicy: None