image:
  repository: frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

deployment:
  replicas: 2
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  host: ""
  tls:
    termination: edge

global:
  namespace: cf-dev
  registry: 818140567777.dkr.ecr.us-east-1.amazonaws.com/consultingfirm
  imagePullSecrets:
    - name: ecr-secret